import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";

import alaska_1 from "../../public/images/alaska-1.jpg";
import alaska_2 from "../../public/images/alaska-2.jpg";
import auto_hero from "../../public/images/auto-hero.jpg";

import flower_1 from "../../public/images/flower-1.jpg";
import flower_2 from "../../public/images/flower-2.jpg";
import flower_3 from "../../public/images/flower-3.jpg";
import flower_4 from "../../public/images/flower-4.jpg";
import fox_image from "../../public/images/fox.jpg";
import rock_image from "../../public/images/rock-1.jpg";
import tree_image_1 from "../../public/images/tree-1.jpg";
import tree_image_2 from "../../public/images/tree-2.jpg";
import yosemite from "../../public/images/yosemite-1.jpg";
// import car_long from '../../public/images/car-long.jpg'
import mecum_1 from "../../public/images/mecum-1.jpg";
import mecum_2 from "../../public/images/mecum-2.jpg";
import mecum_3 from "../../public/images/mecum-3.jpg";
import mecum_4 from "../../public/images/mecum-4.jpg";
import sunset_1 from "../../public/images/sunset-1.jpg";
import sunset_2 from "../../public/images/sunset-2.jpg";
import sunset_3 from "../../public/images/sunset-3.jpg";

// Components
import Image from "next/image";
import Divider from "../components/Divider";
import Hero from "../components/Hero";
import ImageContainer from "../components/ImageContainer";
import Navbar from "../components/Navbar";
import SectionTitle from "../components/SectionTitle";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative grid grid-cols-3 bg-gray-950 pt-24 pt-8 text-white">
        <Navbar />
        <Hero />
        <section
          id="Nature"
          className={`nature relative col-span-7 grid gap-4`}
        >
          <Image src={fox_image} alt="" />
          <h2 className="text-black">Nature</h2>
          <section
            className={`nature--pictures mt-[-1rem] grid grid-cols-7 gap-2`}
          >
            <SectionTitle title={"From Yosemite"} classList={""} />
            <ImageContainer
              classList={"col-span-7 place-self-center"}
              src={yosemite}
              alt=""
              before={""}
              after={""}
            />

            <div className={`column col-span-4 col-start-1 grid`}>
              <ImageContainer
                classList={`column col-span-4 col-start-1`}
                src={tree_image_2}
                alt=""
                before={""}
                after={"Sequoia Tree"}
              />
              <section className={"title-wrapper col-span-4"}>
                <SectionTitle title={"To Alaska"} />
              </section>
            </div>

            <div className={`column col-span-3 grid gap-4`}>
              <ImageContainer
                classList={`column grid col-span-3`}
                src={rock_image}
                alt=""
                before={""}
                // after={'Boulder'}
              />
              <ImageContainer
                classList={`column grid col-span-3`}
                src={tree_image_1}
                alt=""
                before={""}
                // after={'Seqouia'}
              />
            </div>
            <section className={`alaska col-span-7 mt-[-0.5rem] grid gap-4 `}>
              <ImageContainer
                src={alaska_1}
                classList={"col-span-7"}
                before={"Alaska"}
                after={"Ranier's Pass"}
              />
              <ImageContainer
                src={alaska_2}
                classList={"col-span-7"}
                before={""}
                after={"'God Smiling on St. Andrews'"}
              />
            </section>

            <section
              className={`florida align-center col-span-7 grid gap-2 xl:gap-8`}
            >
              <SectionTitle title={"And Back To Florida"} classList={""} />
              <ImageContainer
                classList={`column col-span-4  self-center`}
                src={flower_1}
                alt=""
                before={""}
                // after={'Seqouia'}
              />
              <ImageContainer
                classList={`column grid col-span-3 `}
                src={flower_3}
                alt=""
                before={""}
                // after={'Seqouia'}
              />
              <ImageContainer
                classList={`column grid col-span-3  self-center`}
                src={flower_4}
                alt=""
                before={""}
                // after={'Seqouia'}
              />
              <ImageContainer
                classList={`column grid col-span-4 self-center`}
                src={flower_2}
                alt=""
                before={""}
                // after={'Seqouia'}
              />
            </section>
          </section>
        </section>
        <section id="Auto" className="nature relative col-span-7 grid gap-4">
          <Divider classList={"mt-[0.25rem]"} />
          <Image src={auto_hero} alt="" />
          <h2 className="text-black">Automotive</h2>

          <section className={`auto--pictures grid grid-cols-7 gap-6`}>
            <SectionTitle title={"Mecum Auto Auction"} classList={""} />

            <ImageContainer
              classList={"col-span-7 place-self-center  "}
              src={mecum_1}
              alt=""
              before={""}
              after={""}
            />
            <ImageContainer
              classList={"col-span-4 place-self-center  "}
              src={mecum_2}
              alt=""
              before={""}
              after={""}
            />
            <ImageContainer
              classList={"col-span-3 col-start-5 place-self-center  "}
              src={mecum_4}
              alt=""
              before={""}
              after={""}
            />
            <ImageContainer
              classList={"col-span-7 place-self-center  "}
              src={mecum_3}
              alt=""
              before={""}
              after={""}
            />
          </section>
          <section className={`auto--pictures grid grid-cols-7 gap-6`}>
            <SectionTitle title={"Sunset Walk 2021"} classList={""} />

            <ImageContainer
              classList={"col-span-7 place-self-center  "}
              src={sunset_1}
              alt=""
              before={""}
              after={""}
            />
            <ImageContainer
              classList={"col-span-4 place-self-center  "}
              src={sunset_2}
              alt=""
              before={""}
              after={""}
            />
            <ImageContainer
              classList={"col-span-3 col-start-5 place-self-center  "}
              src={sunset_3}
              alt=""
              before={""}
              after={""}
            />
          </section>
        </section>
      </main>{" "}
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
